# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/testlab/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/firebase/testlab/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.firebase.testlab.v1.TestMatrixEventData" do
      optional :create_time, :message, 1, "google.protobuf.Timestamp"
      optional :state, :enum, 2, "google.events.firebase.testlab.v1.TestState"
      optional :invalid_matrix_details, :string, 3
      optional :outcome_summary, :enum, 4, "google.events.firebase.testlab.v1.OutcomeSummary"
      optional :result_storage, :message, 5, "google.events.firebase.testlab.v1.ResultStorage"
      optional :client_info, :message, 6, "google.events.firebase.testlab.v1.ClientInfo"
      optional :test_matrix_id, :string, 7
    end
    add_message "google.events.firebase.testlab.v1.ClientInfo" do
      optional :client, :string, 1
      map :details, :string, :string, 2
    end
    add_message "google.events.firebase.testlab.v1.ResultStorage" do
      optional :tool_results_history, :string, 1
      optional :tool_results_execution, :string, 2
      optional :results_uri, :string, 3
      optional :gcs_path, :string, 4
    end
    add_enum "google.events.firebase.testlab.v1.TestState" do
      value :TEST_STATE_UNSPECIFIED, 0
      value :VALIDATING, 1
      value :PENDING, 2
      value :FINISHED, 3
      value :ERROR, 4
      value :INVALID, 5
    end
    add_enum "google.events.firebase.testlab.v1.OutcomeSummary" do
      value :OUTCOME_SUMMARY_UNSPECIFIED, 0
      value :SUCCESS, 1
      value :FAILURE, 2
      value :INCONCLUSIVE, 3
      value :SKIPPED, 4
    end
  end
end

module Google
  module Events
    module Firebase
      module TestLab
        module V1
          TestMatrixEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.testlab.v1.TestMatrixEventData").msgclass
          ClientInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.testlab.v1.ClientInfo").msgclass
          ResultStorage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.testlab.v1.ResultStorage").msgclass
          TestState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.testlab.v1.TestState").enummodule
          OutcomeSummary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.testlab.v1.OutcomeSummary").enummodule
        end
      end
    end
  end
end
