# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/testlab/v1/events.proto

require 'google/protobuf'

require 'google/events/cloudevent_pb'
require 'google/events/firebase/testlab/v1/data_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/firebase/testlab/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.firebase.testlab.v1.TestMatrixCompletedEvent" do
      optional :data, :message, 1, "google.events.firebase.testlab.v1.TestMatrixEventData"
    end
  end
end

module Google
  module Events
    module Firebase
      module TestLab
        module V1
          TestMatrixCompletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.testlab.v1.TestMatrixCompletedEvent").msgclass
        end
      end
    end
  end
end
