# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/testlab/v1/events.proto

require 'google/protobuf'

require 'google/events/cloudevent_pb'
require 'google/events/firebase/testlab/v1/data_pb'


descriptor_data = "\n.google/events/firebase/testlab/v1/events.proto\x12!google.events.firebase.testlab.v1\x1a\x1egoogle/events/cloudevent.proto\x1a,google/events/firebase/testlab/v1/data.proto\"\x96\x01\n\x18TestMatrixCompletedEvent\x12\x44\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x36.google.events.firebase.testlab.v1.TestMatrixEventData:4\xb2\xf8\xd8,/google.firebase.testlab.testMatrix.v1.completedB\x8f\x01\xaa\x02*Google.Events.Protobuf.Firebase.TestLab.V1\xca\x02!Google\\Events\\Firebase\\TestLab\\V1\xea\x02%Google::Events::Firebase::TestLab::V1\xba\xf8\xd8,\x11\x46irebase Test Labb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Events
    module Firebase
      module TestLab
        module V1
          TestMatrixCompletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.testlab.v1.TestMatrixCompletedEvent").msgclass
        end
      end
    end
  end
end
