# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/apigeeregistry/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/apigeeregistry/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.cloud.apigeeregistry.v1.Instance" do
      optional :name, :string, 1
      optional :create_time, :message, 2, "google.protobuf.Timestamp"
      optional :update_time, :message, 3, "google.protobuf.Timestamp"
      optional :state, :enum, 4, "google.events.cloud.apigeeregistry.v1.Instance.State"
      optional :state_message, :string, 5
      optional :config, :message, 6, "google.events.cloud.apigeeregistry.v1.Instance.Config"
    end
    add_message "google.events.cloud.apigeeregistry.v1.Instance.Config" do
      optional :location, :string, 1
      optional :cmek_key_name, :string, 2
    end
    add_enum "google.events.cloud.apigeeregistry.v1.Instance.State" do
      value :STATE_UNSPECIFIED, 0
      value :INACTIVE, 1
      value :CREATING, 2
      value :ACTIVE, 3
      value :UPDATING, 4
      value :DELETING, 5
      value :FAILED, 6
    end
    add_message "google.events.cloud.apigeeregistry.v1.Api" do
      optional :name, :string, 1
      optional :display_name, :string, 2
      optional :description, :string, 3
      optional :create_time, :message, 4, "google.protobuf.Timestamp"
      optional :update_time, :message, 5, "google.protobuf.Timestamp"
      optional :availability, :string, 6
      optional :recommended_version, :string, 7
      optional :recommended_deployment, :string, 8
      map :labels, :string, :string, 9
      map :annotations, :string, :string, 10
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiVersion" do
      optional :name, :string, 1
      optional :display_name, :string, 2
      optional :description, :string, 3
      optional :create_time, :message, 4, "google.protobuf.Timestamp"
      optional :update_time, :message, 5, "google.protobuf.Timestamp"
      optional :state, :string, 6
      map :labels, :string, :string, 7
      map :annotations, :string, :string, 8
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiSpec" do
      optional :name, :string, 1
      optional :filename, :string, 2
      optional :description, :string, 3
      optional :revision_id, :string, 4
      optional :create_time, :message, 5, "google.protobuf.Timestamp"
      optional :revision_create_time, :message, 6, "google.protobuf.Timestamp"
      optional :revision_update_time, :message, 7, "google.protobuf.Timestamp"
      optional :mime_type, :string, 8
      optional :size_bytes, :int32, 9
      optional :hash, :string, 10
      optional :source_uri, :string, 11
      map :labels, :string, :string, 14
      map :annotations, :string, :string, 15
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiDeployment" do
      optional :name, :string, 1
      optional :display_name, :string, 2
      optional :description, :string, 3
      optional :revision_id, :string, 4
      optional :create_time, :message, 5, "google.protobuf.Timestamp"
      optional :revision_create_time, :message, 6, "google.protobuf.Timestamp"
      optional :revision_update_time, :message, 7, "google.protobuf.Timestamp"
      optional :api_spec_revision, :string, 8
      optional :endpoint_uri, :string, 9
      optional :external_channel_uri, :string, 10
      optional :intended_audience, :string, 11
      optional :access_guidance, :string, 12
      map :labels, :string, :string, 14
      map :annotations, :string, :string, 15
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiVersionEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiVersion"
    end
    add_message "google.events.cloud.apigeeregistry.v1.InstanceEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.apigeeregistry.v1.Instance"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiSpecEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiSpec"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiDeploymentEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiDeployment"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.apigeeregistry.v1.Api"
    end
  end
end

module Google
  module Events
    module Cloud
      module ApigeeRegistry
        module V1
          Instance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.Instance").msgclass
          Instance::Config = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.Instance.Config").msgclass
          Instance::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.Instance.State").enummodule
          Api = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.Api").msgclass
          ApiVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiVersion").msgclass
          ApiSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiSpec").msgclass
          ApiDeployment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiDeployment").msgclass
          ApiVersionEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiVersionEventData").msgclass
          InstanceEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.InstanceEventData").msgclass
          ApiSpecEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiSpecEventData").msgclass
          ApiDeploymentEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiDeploymentEventData").msgclass
          ApiEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiEventData").msgclass
        end
      end
    end
  end
end
