# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/apigeeregistry/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/apigeeregistry/v1/data_pb'
require 'google/events/cloudevent_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/apigeeregistry/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.cloud.apigeeregistry.v1.InstanceCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.InstanceEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.InstanceDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.InstanceEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiUpdatedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiVersionCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiVersionEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiVersionUpdatedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiVersionEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiVersionDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiVersionEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiSpecCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiSpecEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiSpecUpdatedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiSpecEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiSpecDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiSpecEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiDeploymentCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiDeploymentEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiDeploymentUpdatedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiDeploymentEventData"
    end
    add_message "google.events.cloud.apigeeregistry.v1.ApiDeploymentDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.apigeeregistry.v1.ApiDeploymentEventData"
    end
  end
end

module Google
  module Events
    module Cloud
      module ApigeeRegistry
        module V1
          InstanceCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.InstanceCreatedEvent").msgclass
          InstanceDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.InstanceDeletedEvent").msgclass
          ApiCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiCreatedEvent").msgclass
          ApiUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiUpdatedEvent").msgclass
          ApiDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiDeletedEvent").msgclass
          ApiVersionCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiVersionCreatedEvent").msgclass
          ApiVersionUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiVersionUpdatedEvent").msgclass
          ApiVersionDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiVersionDeletedEvent").msgclass
          ApiSpecCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiSpecCreatedEvent").msgclass
          ApiSpecUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiSpecUpdatedEvent").msgclass
          ApiSpecDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiSpecDeletedEvent").msgclass
          ApiDeploymentCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiDeploymentCreatedEvent").msgclass
          ApiDeploymentUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiDeploymentUpdatedEvent").msgclass
          ApiDeploymentDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.apigeeregistry.v1.ApiDeploymentDeletedEvent").msgclass
        end
      end
    end
  end
end
