inherit_gem:
  google-style: google-style.yml

AllCops:
  Include:
    - "lib/**/*.rb"
    - "Gemfile"
    - "google-events.gemspec"
  Exclude:
    - "lib/**/*_pb.rb"

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "test/**/test_*.rb"
Metrics/BlockLength:
  Exclude:
    - "test/**/test_*.rb"
    - "google-events.gemspec"
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Naming/FileName:
  Exclude:
    - ".toys/**/*.rb"
    - "lib/google-events.rb"
Style/BlockDelimiters:
  Exclude:
    - "test/**/test_*.rb"
