# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/firestore/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
require 'google/protobuf/timestamp_pb'
require 'google/type/latlng_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/firestore/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.cloud.firestore.v1.DocumentEventData" do
      optional :value, :message, 1, "google.events.cloud.firestore.v1.Document"
      optional :old_value, :message, 2, "google.events.cloud.firestore.v1.Document"
      optional :update_mask, :message, 3, "google.events.cloud.firestore.v1.DocumentMask"
      map :wildcards, :string, :string, 4
    end
    add_message "google.events.cloud.firestore.v1.DocumentMask" do
      repeated :field_paths, :string, 1
    end
    add_message "google.events.cloud.firestore.v1.Document" do
      optional :name, :string, 1
      map :fields, :string, :message, 2, "google.events.cloud.firestore.v1.Value"
      optional :create_time, :message, 3, "google.protobuf.Timestamp"
      optional :update_time, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "google.events.cloud.firestore.v1.Value" do
      oneof :value_type do
        optional :null_value, :enum, 11, "google.protobuf.NullValue"
        optional :boolean_value, :bool, 1
        optional :integer_value, :int64, 2
        optional :double_value, :double, 3
        optional :timestamp_value, :message, 10, "google.protobuf.Timestamp"
        optional :string_value, :string, 17
        optional :bytes_value, :bytes, 18
        optional :reference_value, :string, 5
        optional :geo_point_value, :message, 8, "google.type.LatLng"
        optional :array_value, :message, 9, "google.events.cloud.firestore.v1.ArrayValue"
        optional :map_value, :message, 6, "google.events.cloud.firestore.v1.MapValue"
      end
    end
    add_message "google.events.cloud.firestore.v1.ArrayValue" do
      repeated :values, :message, 1, "google.events.cloud.firestore.v1.Value"
    end
    add_message "google.events.cloud.firestore.v1.MapValue" do
      map :fields, :string, :message, 1, "google.events.cloud.firestore.v1.Value"
    end
  end
end

module Google
  module Events
    module Cloud
      module Firestore
        module V1
          DocumentEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.firestore.v1.DocumentEventData").msgclass
          DocumentMask = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.firestore.v1.DocumentMask").msgclass
          Document = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.firestore.v1.Document").msgclass
          Value = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.firestore.v1.Value").msgclass
          ArrayValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.firestore.v1.ArrayValue").msgclass
          MapValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.firestore.v1.MapValue").msgclass
        end
      end
    end
  end
end
