# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/beyondcorp/appconnections/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/beyondcorp/appconnections/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.cloud.beyondcorp.appconnections.v1.AppConnection" do
      optional :name, :string, 1
      optional :create_time, :message, 2, "google.protobuf.Timestamp"
      optional :update_time, :message, 3, "google.protobuf.Timestamp"
      map :labels, :string, :string, 4
      optional :display_name, :string, 5
      optional :uid, :string, 6
      optional :type, :enum, 7, "google.events.cloud.beyondcorp.appconnections.v1.AppConnection.Type"
      optional :application_endpoint, :message, 8, "google.events.cloud.beyondcorp.appconnections.v1.AppConnection.ApplicationEndpoint"
      repeated :connectors, :string, 9
      optional :state, :enum, 10, "google.events.cloud.beyondcorp.appconnections.v1.AppConnection.State"
      optional :gateway, :message, 11, "google.events.cloud.beyondcorp.appconnections.v1.AppConnection.Gateway"
    end
    add_message "google.events.cloud.beyondcorp.appconnections.v1.AppConnection.ApplicationEndpoint" do
      optional :host, :string, 1
      optional :port, :int32, 2
    end
    add_message "google.events.cloud.beyondcorp.appconnections.v1.AppConnection.Gateway" do
      optional :type, :enum, 2, "google.events.cloud.beyondcorp.appconnections.v1.AppConnection.Gateway.Type"
      optional :uri, :string, 3
      optional :ingress_port, :int32, 4
      optional :app_gateway, :string, 5
      optional :l7psc, :string, 6
    end
    add_enum "google.events.cloud.beyondcorp.appconnections.v1.AppConnection.Gateway.Type" do
      value :TYPE_UNSPECIFIED, 0
      value :GCP_REGIONAL_MIG, 1
    end
    add_enum "google.events.cloud.beyondcorp.appconnections.v1.AppConnection.Type" do
      value :TYPE_UNSPECIFIED, 0
      value :TCP_PROXY, 1
    end
    add_enum "google.events.cloud.beyondcorp.appconnections.v1.AppConnection.State" do
      value :STATE_UNSPECIFIED, 0
      value :CREATING, 1
      value :CREATED, 2
      value :UPDATING, 3
      value :DELETING, 4
      value :DOWN, 5
    end
    add_message "google.events.cloud.beyondcorp.appconnections.v1.AppConnectionEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.beyondcorp.appconnections.v1.AppConnection"
    end
  end
end

module Google
  module Events
    module Cloud
      module BeyondCorp
        module AppConnections
          module V1
            AppConnection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnections.v1.AppConnection").msgclass
            AppConnection::ApplicationEndpoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnections.v1.AppConnection.ApplicationEndpoint").msgclass
            AppConnection::Gateway = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnections.v1.AppConnection.Gateway").msgclass
            AppConnection::Gateway::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnections.v1.AppConnection.Gateway.Type").enummodule
            AppConnection::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnections.v1.AppConnection.Type").enummodule
            AppConnection::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnections.v1.AppConnection.State").enummodule
            AppConnectionEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnections.v1.AppConnectionEventData").msgclass
          end
        end
      end
    end
  end
end
