# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/beyondcorp/appconnections/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/beyondcorp/appconnections/v1/data_pb'
require 'google/events/cloudevent_pb'


descriptor_data = "\n=google/events/cloud/beyondcorp/appconnections/v1/events.proto\x12\x30google.events.cloud.beyondcorp.appconnections.v1\x1a;google/events/cloud/beyondcorp/appconnections/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\xcb\x01\n\x19\x41ppConnectionCreatedEvent\x12V\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32H.google.events.cloud.beyondcorp.appconnections.v1.AppConnectionEventData:V\xb2\xf8\xd8,?google.cloud.beyondcorp.appconnections.appConnection.v1.created\xca\xf8\xd8,\rappconnection\"\xcb\x01\n\x19\x41ppConnectionUpdatedEvent\x12V\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32H.google.events.cloud.beyondcorp.appconnections.v1.AppConnectionEventData:V\xb2\xf8\xd8,?google.cloud.beyondcorp.appconnections.appConnection.v1.updated\xca\xf8\xd8,\rappconnection\"\xcb\x01\n\x19\x41ppConnectionDeletedEvent\x12V\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32H.google.events.cloud.beyondcorp.appconnections.v1.AppConnectionEventData:V\xb2\xf8\xd8,?google.cloud.beyondcorp.appconnections.appConnection.v1.deleted\xca\xf8\xd8,\rappconnectionB\x95\x02\xaa\x02\x39Google.Events.Protobuf.Cloud.BeyondCorp.AppConnections.V1\xca\x02\x30Google\\Events\\Cloud\\BeyondCorp\\AppConnections\\V1\xea\x02\x35Google::Events::Cloud::BeyondCorp::AppConnections::V1\xba\xf8\xd8,\nBeyondCorp\xc2\xf8\xd8,Z\n\rappconnection\x12:The resource ID of the AppConnection triggering the event.\x1a\rappConnectionb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Events
    module Cloud
      module BeyondCorp
        module AppConnections
          module V1
            AppConnectionCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnections.v1.AppConnectionCreatedEvent").msgclass
            AppConnectionUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnections.v1.AppConnectionUpdatedEvent").msgclass
            AppConnectionDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnections.v1.AppConnectionDeletedEvent").msgclass
          end
        end
      end
    end
  end
end
