# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/beyondcorp/clientconnectorservices/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/beyondcorp/clientconnectorservices/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService" do
      optional :name, :string, 1
      optional :create_time, :message, 2, "google.protobuf.Timestamp"
      optional :update_time, :message, 3, "google.protobuf.Timestamp"
      optional :display_name, :string, 4
      optional :ingress, :message, 6, "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress"
      optional :egress, :message, 7, "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Egress"
      optional :state, :enum, 8, "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.State"
    end
    add_message "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress" do
      oneof :ingress_config do
        optional :config, :message, 1, "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress.Config"
      end
    end
    add_message "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress.Config" do
      optional :transport_protocol, :enum, 1, "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress.Config.TransportProtocol"
      repeated :destination_routes, :message, 2, "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress.Config.DestinationRoute"
    end
    add_message "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress.Config.DestinationRoute" do
      optional :address, :string, 1
      optional :netmask, :string, 2
    end
    add_enum "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress.Config.TransportProtocol" do
      value :TRANSPORT_PROTOCOL_UNSPECIFIED, 0
      value :TCP, 1
    end
    add_message "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Egress" do
      oneof :destination_type do
        optional :peered_vpc, :message, 1, "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Egress.PeeredVpc"
      end
    end
    add_message "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Egress.PeeredVpc" do
      optional :network_vpc, :string, 1
    end
    add_enum "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.State" do
      value :STATE_UNSPECIFIED, 0
      value :CREATING, 1
      value :UPDATING, 2
      value :DELETING, 3
      value :RUNNING, 4
      value :DOWN, 5
      value :ERROR, 6
    end
    add_message "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorServiceEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService"
    end
  end
end

module Google
  module Events
    module Cloud
      module BeyondCorp
        module ClientConnectorServices
          module V1
            ClientConnectorService = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService").msgclass
            ClientConnectorService::Ingress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress").msgclass
            ClientConnectorService::Ingress::Config = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress.Config").msgclass
            ClientConnectorService::Ingress::Config::DestinationRoute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress.Config.DestinationRoute").msgclass
            ClientConnectorService::Ingress::Config::TransportProtocol = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Ingress.Config.TransportProtocol").enummodule
            ClientConnectorService::Egress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Egress").msgclass
            ClientConnectorService::Egress::PeeredVpc = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.Egress.PeeredVpc").msgclass
            ClientConnectorService::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorService.State").enummodule
            ClientConnectorServiceEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientconnectorservices.v1.ClientConnectorServiceEventData").msgclass
          end
        end
      end
    end
  end
end
