# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/geminicloudassist/v1/data.proto

require 'google/protobuf'


descriptor_data = "\n3google/events/cloud/geminicloudassist/v1/data.proto\x12(google.events.cloud.geminicloudassist.v1\"?\n\rTaskEventData\x12\x1f\n\x17result_object_reference\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\tB\x8e\x01\xaa\x02\x31Google.Events.Protobuf.Cloud.GeminiCloudAssist.V1\xca\x02(Google\\Events\\Cloud\\GeminiCloudAssist\\V1\xea\x02,Google::Events::Cloud::GeminiCloudAssist::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Events
    module Cloud
      module GeminiCloudAssist
        module V1
          TaskEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.geminicloudassist.v1.TaskEventData").msgclass
        end
      end
    end
  end
end
