# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/geminicloudassist/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/geminicloudassist/v1/data_pb'
require 'google/events/cloudevent_pb'


descriptor_data = "\n5google/events/cloud/geminicloudassist/v1/events.proto\x12(google.events.cloud.geminicloudassist.v1\x1a\x33google/events/cloud/geminicloudassist/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\xa0\x01\n\x12TaskCompletedEvent\x12\x45\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x37.google.events.cloud.geminicloudassist.v1.TaskEventData:C\xb2\xf8\xd8,0google.cloud.geminicloudassist.task.v1.completed\xca\xf8\xd8,\tproactiveB\xa1\x02\xaa\x02\x31Google.Events.Protobuf.Cloud.GeminiCloudAssist.V1\xca\x02(Google\\Events\\Cloud\\GeminiCloudAssist\\V1\xea\x02,Google::Events::Cloud::GeminiCloudAssist::V1\xba\xf8\xd8,\x13Gemini Cloud Assist\xc2\xf8\xd8,v\n\tproactive\x12^This field will be set to true if the task is executed proactively. Set to false in otherwise.\x1a\tproactiveb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Events
    module Cloud
      module GeminiCloudAssist
        module V1
          TaskCompletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.geminicloudassist.v1.TaskCompletedEvent").msgclass
        end
      end
    end
  end
end
