# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/datafusion/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/datafusion/v1/data_pb'
require 'google/events/cloudevent_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/datafusion/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.cloud.datafusion.v1.InstanceCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.datafusion.v1.InstanceEventData"
    end
    add_message "google.events.cloud.datafusion.v1.InstanceDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.datafusion.v1.InstanceEventData"
    end
    add_message "google.events.cloud.datafusion.v1.InstanceUpdatedEvent" do
      optional :data, :message, 1, "google.events.cloud.datafusion.v1.InstanceEventData"
    end
    add_message "google.events.cloud.datafusion.v1.DnsPeeringCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.datafusion.v1.DnsPeeringEventData"
    end
    add_message "google.events.cloud.datafusion.v1.DnsPeeringDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.datafusion.v1.DnsPeeringEventData"
    end
  end
end

module Google
  module Events
    module Cloud
      module DataFusion
        module V1
          InstanceCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datafusion.v1.InstanceCreatedEvent").msgclass
          InstanceDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datafusion.v1.InstanceDeletedEvent").msgclass
          InstanceUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datafusion.v1.InstanceUpdatedEvent").msgclass
          DnsPeeringCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datafusion.v1.DnsPeeringCreatedEvent").msgclass
          DnsPeeringDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datafusion.v1.DnsPeeringDeletedEvent").msgclass
        end
      end
    end
  end
end
