# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/datafusion/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/datafusion/v1/data_pb'
require 'google/events/cloudevent_pb'


descriptor_data = "\n.google/events/cloud/datafusion/v1/events.proto\x12!google.events.cloud.datafusion.v1\x1a,google/events/cloud/datafusion/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\x99\x01\n\x14InstanceCreatedEvent\x12\x42\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x34.google.events.cloud.datafusion.v1.InstanceEventData:=\xb2\xf8\xd8,+google.cloud.datafusion.instance.v1.created\xca\xf8\xd8,\x08instance\"\x99\x01\n\x14InstanceDeletedEvent\x12\x42\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x34.google.events.cloud.datafusion.v1.InstanceEventData:=\xb2\xf8\xd8,+google.cloud.datafusion.instance.v1.deleted\xca\xf8\xd8,\x08instance\"\x99\x01\n\x14InstanceUpdatedEvent\x12\x42\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x34.google.events.cloud.datafusion.v1.InstanceEventData:=\xb2\xf8\xd8,+google.cloud.datafusion.instance.v1.updated\xca\xf8\xd8,\x08instance\"\xae\x01\n\x16\x44nsPeeringCreatedEvent\x12\x44\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x36.google.events.cloud.datafusion.v1.DnsPeeringEventData:N\xb2\xf8\xd8,-google.cloud.datafusion.dnsPeering.v1.created\xca\xf8\xd8,\x08instance\xca\xf8\xd8,\ndnspeering\"\xae\x01\n\x16\x44nsPeeringDeletedEvent\x12\x44\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x36.google.events.cloud.datafusion.v1.DnsPeeringEventData:N\xb2\xf8\xd8,-google.cloud.datafusion.dnsPeering.v1.deleted\xca\xf8\xd8,\x08instance\xca\xf8\xd8,\ndnspeeringB\xab\x02\xaa\x02*Google.Events.Protobuf.Cloud.DataFusion.V1\xca\x02!Google\\Events\\Cloud\\DataFusion\\V1\xea\x02%Google::Events::Cloud::DataFusion::V1\xba\xf8\xd8,\x11\x43loud Data Fusion\xc2\xf8\xd8,A\n\x08instance\x12\x35The resource ID of the Instance triggering the event.\xc2\xf8\xd8,Q\n\ndnspeering\x12\x37The resource ID of the DnsPeering triggering the event.\x1a\ndnsPeeringb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Events
    module Cloud
      module DataFusion
        module V1
          InstanceCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datafusion.v1.InstanceCreatedEvent").msgclass
          InstanceDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datafusion.v1.InstanceDeletedEvent").msgclass
          InstanceUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datafusion.v1.InstanceUpdatedEvent").msgclass
          DnsPeeringCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datafusion.v1.DnsPeeringCreatedEvent").msgclass
          DnsPeeringDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datafusion.v1.DnsPeeringDeletedEvent").msgclass
        end
      end
    end
  end
end
