# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/firebase/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.firebase.v1.DocumentEventData" do
      optional :data, :message, 1, "google.protobuf.Value"
      optional :delta, :message, 2, "google.protobuf.Value"
      map :wildcards, :string, :string, 3
    end
  end
end

module Google
  module Events
    module Firebase
      module V1
        DocumentEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.v1.DocumentEventData").msgclass
      end
    end
  end
end
