# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/audit/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
require 'google/rpc/status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/audit/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.cloud.audit.v1.AuditLogData" do
      optional :service_name, :string, 7
      optional :method_name, :string, 8
      optional :resource_name, :string, 11
      optional :num_response_items, :int64, 12
      optional :status, :message, 2, "google.rpc.Status"
      optional :authentication_info, :message, 3, "google.events.cloud.audit.v1.AuthenticationInfo"
      repeated :authorization_info, :message, 9, "google.events.cloud.audit.v1.AuthorizationInfo"
      optional :request_metadata, :message, 4, "google.events.cloud.audit.v1.RequestMetadata"
      optional :request, :message, 16, "google.protobuf.Struct"
      optional :response, :message, 17, "google.protobuf.Struct"
      optional :service_data, :message, 15, "google.protobuf.Struct"
    end
    add_message "google.events.cloud.audit.v1.AuthenticationInfo" do
      optional :principal_email, :string, 1
    end
    add_message "google.events.cloud.audit.v1.AuthorizationInfo" do
      optional :resource, :string, 1
      optional :permission, :string, 2
      optional :granted, :bool, 3
    end
    add_message "google.events.cloud.audit.v1.RequestMetadata" do
      optional :caller_ip, :string, 1
      optional :caller_supplied_user_agent, :string, 2
    end
  end
end

module Google
  module Events
    module Cloud
      module Audit
        module V1
          AuditLogData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.audit.v1.AuditLogData").msgclass
          AuthenticationInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.audit.v1.AuthenticationInfo").msgclass
          AuthorizationInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.audit.v1.AuthorizationInfo").msgclass
          RequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.audit.v1.RequestMetadata").msgclass
        end
      end
    end
  end
end
