# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/workflows/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n+google/events/cloud/workflows/v1/data.proto\x12 google.events.cloud.workflows.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x04\n\x08Workflow\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12?\n\x05state\x18\x03 \x01(\x0e\x32\x30.google.events.cloud.workflows.v1.Workflow.State\x12\x13\n\x0brevision_id\x18\x04 \x01(\t\x12/\n\x0b\x63reate_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bupdate_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x38\n\x14revision_create_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x46\n\x06labels\x18\x08 \x03(\x0b\x32\x36.google.events.cloud.workflows.v1.Workflow.LabelsEntry\x12\x17\n\x0fservice_account\x18\t \x01(\t\x12\x19\n\x0fsource_contents\x18\n \x01(\tH\x00\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"*\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x42\r\n\x0bsource_code\"a\n\x11WorkflowEventData\x12@\n\x07payload\x18\x01 \x01(\x0b\x32*.google.events.cloud.workflows.v1.WorkflowH\x00\x88\x01\x01\x42\n\n\x08_payloadBv\xaa\x02)Google.Events.Protobuf.Cloud.Workflows.V1\xca\x02 Google\\Events\\Cloud\\Workflows\\V1\xea\x02$Google::Events::Cloud::Workflows::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.protobuf.Timestamp", "google/protobuf/timestamp.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Events
    module Cloud
      module Workflows
        module V1
          Workflow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.workflows.v1.Workflow").msgclass
          Workflow::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.workflows.v1.Workflow.State").enummodule
          WorkflowEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.workflows.v1.WorkflowEventData").msgclass
        end
      end
    end
  end
end
