# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/workflows/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/workflows/v1/data_pb'
require 'google/events/cloudevent_pb'


descriptor_data = "\n-google/events/cloud/workflows/v1/events.proto\x12 google.events.cloud.workflows.v1\x1a+google/events/cloud/workflows/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\x97\x01\n\x14WorkflowCreatedEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.workflows.v1.WorkflowEventData:<\xb2\xf8\xd8,*google.cloud.workflows.workflow.v1.created\xca\xf8\xd8,\x08workflow\"\x97\x01\n\x14WorkflowDeletedEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.workflows.v1.WorkflowEventData:<\xb2\xf8\xd8,*google.cloud.workflows.workflow.v1.deleted\xca\xf8\xd8,\x08workflow\"\x97\x01\n\x14WorkflowUpdatedEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.workflows.v1.WorkflowEventData:<\xb2\xf8\xd8,*google.cloud.workflows.workflow.v1.updated\xca\xf8\xd8,\x08workflowB\xca\x01\xaa\x02)Google.Events.Protobuf.Cloud.Workflows.V1\xca\x02 Google\\Events\\Cloud\\Workflows\\V1\xea\x02$Google::Events::Cloud::Workflows::V1\xba\xf8\xd8,\tWorkflows\xc2\xf8\xd8,A\n\x08workflow\x12\x35The resource ID of the Workflow triggering the event.b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.events.cloud.workflows.v1.WorkflowEventData", "google/events/cloud/workflows/v1/data.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Events
    module Cloud
      module Workflows
        module V1
          WorkflowCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.workflows.v1.WorkflowCreatedEvent").msgclass
          WorkflowDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.workflows.v1.WorkflowDeletedEvent").msgclass
          WorkflowUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.workflows.v1.WorkflowUpdatedEvent").msgclass
        end
      end
    end
  end
end
