# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/pubsub/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/pubsub/v1/data_pb'
require 'google/events/cloudevent_pb'


descriptor_data = "\n*google/events/cloud/pubsub/v1/events.proto\x12\x1dgoogle.events.cloud.pubsub.v1\x1a(google/events/cloud/pubsub/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\x98\x01\n\x15MessagePublishedEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.pubsub.v1.MessagePublishedData:<\xb2\xf8\xd8,-google.cloud.pubsub.topic.v1.messagePublished\xca\xf8\xd8,\x05topicB\xc3\x01\xaa\x02&Google.Events.Protobuf.Cloud.PubSub.V1\xca\x02\x1dGoogle\\Events\\Cloud\\PubSub\\V1\xea\x02!Google::Events::Cloud::PubSub::V1\xba\xf8\xd8,\rCloud Pub/Sub\xc2\xf8\xd8,?\n\x05topic\x12\x36The Pub/Sub topic for which the message was published.b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Events
    module Cloud
      module PubSub
        module V1
          MessagePublishedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.pubsub.v1.MessagePublishedEvent").msgclass
        end
      end
    end
  end
end
