# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/pubsub/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/pubsub/v1/data_pb'
require 'google/events/cloudevent_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/pubsub/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.cloud.pubsub.v1.MessagePublishedEvent" do
      optional :data, :message, 1, "google.events.cloud.pubsub.v1.MessagePublishedData"
    end
  end
end

module Google
  module Events
    module Cloud
      module PubSub
        module V1
          MessagePublishedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.pubsub.v1.MessagePublishedEvent").msgclass
        end
      end
    end
  end
end
