# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/audit/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/audit/v1/data_pb'
require 'google/events/cloudevent_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/audit/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.cloud.audit.v1.AuditLogWrittenEvent" do
      optional :data, :message, 1, "google.events.cloud.audit.v1.LogEntryData"
    end
  end
end

module Google
  module Events
    module Cloud
      module Audit
        module V1
          AuditLogWrittenEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.audit.v1.AuditLogWrittenEvent").msgclass
        end
      end
    end
  end
end
