# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/beyondcorp/clientgateways/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/beyondcorp/clientgateways/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.cloud.beyondcorp.clientgateways.v1.ClientGateway" do
      optional :name, :string, 1
      optional :create_time, :message, 2, "google.protobuf.Timestamp"
      optional :update_time, :message, 3, "google.protobuf.Timestamp"
      optional :state, :enum, 4, "google.events.cloud.beyondcorp.clientgateways.v1.ClientGateway.State"
      optional :id, :string, 5
      optional :client_connector_service, :string, 6
    end
    add_enum "google.events.cloud.beyondcorp.clientgateways.v1.ClientGateway.State" do
      value :STATE_UNSPECIFIED, 0
      value :CREATING, 1
      value :UPDATING, 2
      value :DELETING, 3
      value :RUNNING, 4
      value :DOWN, 5
      value :ERROR, 6
    end
    add_message "google.events.cloud.beyondcorp.clientgateways.v1.ClientGatewayEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.beyondcorp.clientgateways.v1.ClientGateway"
    end
  end
end

module Google
  module Events
    module Cloud
      module BeyondCorp
        module ClientGateways
          module V1
            ClientGateway = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientgateways.v1.ClientGateway").msgclass
            ClientGateway::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientgateways.v1.ClientGateway.State").enummodule
            ClientGatewayEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientgateways.v1.ClientGatewayEventData").msgclass
          end
        end
      end
    end
  end
end
