# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/beyondcorp/clientgateways/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/beyondcorp/clientgateways/v1/data_pb'
require 'google/events/cloudevent_pb'


descriptor_data = "\n=google/events/cloud/beyondcorp/clientgateways/v1/events.proto\x12\x30google.events.cloud.beyondcorp.clientgateways.v1\x1a;google/events/cloud/beyondcorp/clientgateways/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\xcb\x01\n\x19\x43lientGatewayCreatedEvent\x12V\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32H.google.events.cloud.beyondcorp.clientgateways.v1.ClientGatewayEventData:V\xb2\xf8\xd8,?google.cloud.beyondcorp.clientgateways.clientGateway.v1.created\xca\xf8\xd8,\rclientgateway\"\xcb\x01\n\x19\x43lientGatewayDeletedEvent\x12V\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32H.google.events.cloud.beyondcorp.clientgateways.v1.ClientGatewayEventData:V\xb2\xf8\xd8,?google.cloud.beyondcorp.clientgateways.clientGateway.v1.deleted\xca\xf8\xd8,\rclientgatewayB\x95\x02\xaa\x02\x39Google.Events.Protobuf.Cloud.BeyondCorp.ClientGateways.V1\xca\x02\x30Google\\Events\\Cloud\\BeyondCorp\\ClientGateways\\V1\xea\x02\x35Google::Events::Cloud::BeyondCorp::ClientGateways::V1\xba\xf8\xd8,\nBeyondCorp\xc2\xf8\xd8,Z\n\rclientgateway\x12:The resource ID of the ClientGateway triggering the event.\x1a\rclientGatewayb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.events.cloud.beyondcorp.clientgateways.v1.ClientGatewayEventData", "google/events/cloud/beyondcorp/clientgateways/v1/data.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Events
    module Cloud
      module BeyondCorp
        module ClientGateways
          module V1
            ClientGatewayCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientgateways.v1.ClientGatewayCreatedEvent").msgclass
            ClientGatewayDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.clientgateways.v1.ClientGatewayDeletedEvent").msgclass
          end
        end
      end
    end
  end
end
