# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/beyondcorp/appgateways/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/beyondcorp/appgateways/v1/data_pb'
require 'google/events/cloudevent_pb'


descriptor_data = "\n:google/events/cloud/beyondcorp/appgateways/v1/events.proto\x12-google.events.cloud.beyondcorp.appgateways.v1\x1a\x38google/events/cloud/beyondcorp/appgateways/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\xb9\x01\n\x16\x41ppGatewayCreatedEvent\x12P\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x42.google.events.cloud.beyondcorp.appgateways.v1.AppGatewayEventData:M\xb2\xf8\xd8,9google.cloud.beyondcorp.appgateways.appGateway.v1.created\xca\xf8\xd8,\nappgateway\"\xb9\x01\n\x16\x41ppGatewayDeletedEvent\x12P\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x42.google.events.cloud.beyondcorp.appgateways.v1.AppGatewayEventData:M\xb2\xf8\xd8,9google.cloud.beyondcorp.appgateways.appGateway.v1.deleted\xca\xf8\xd8,\nappgatewayB\x83\x02\xaa\x02\x36Google.Events.Protobuf.Cloud.BeyondCorp.AppGateways.V1\xca\x02-Google\\Events\\Cloud\\BeyondCorp\\AppGateways\\V1\xea\x02\x32Google::Events::Cloud::BeyondCorp::AppGateways::V1\xba\xf8\xd8,\nBeyondCorp\xc2\xf8\xd8,Q\n\nappgateway\x12\x37The resource ID of the AppGateway triggering the event.\x1a\nappGatewayb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Events
    module Cloud
      module BeyondCorp
        module AppGateways
          module V1
            AppGatewayCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appgateways.v1.AppGatewayCreatedEvent").msgclass
            AppGatewayDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appgateways.v1.AppGatewayDeletedEvent").msgclass
          end
        end
      end
    end
  end
end
