# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/beyondcorp/appgateways/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/beyondcorp/appgateways/v1/data_pb'
require 'google/events/cloudevent_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/beyondcorp/appgateways/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.cloud.beyondcorp.appgateways.v1.AppGatewayCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.beyondcorp.appgateways.v1.AppGatewayEventData"
    end
    add_message "google.events.cloud.beyondcorp.appgateways.v1.AppGatewayDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.beyondcorp.appgateways.v1.AppGatewayEventData"
    end
  end
end

module Google
  module Events
    module Cloud
      module BeyondCorp
        module AppGateways
          module V1
            AppGatewayCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appgateways.v1.AppGatewayCreatedEvent").msgclass
            AppGatewayDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appgateways.v1.AppGatewayDeletedEvent").msgclass
          end
        end
      end
    end
  end
end
