# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/remoteconfig/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/firebase/remoteconfig/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.firebase.remoteconfig.v1.RemoteConfigEventData" do
      optional :version_number, :int64, 1
      optional :update_time, :message, 2, "google.protobuf.Timestamp"
      optional :update_user, :message, 3, "google.events.firebase.remoteconfig.v1.RemoteConfigUser"
      optional :description, :string, 4
      optional :update_origin, :enum, 5, "google.events.firebase.remoteconfig.v1.RemoteConfigUpdateOrigin"
      optional :update_type, :enum, 6, "google.events.firebase.remoteconfig.v1.RemoteConfigUpdateType"
      optional :rollback_source, :int64, 7
    end
    add_message "google.events.firebase.remoteconfig.v1.RemoteConfigUser" do
      optional :name, :string, 1
      optional :email, :string, 2
      optional :image_url, :string, 3
    end
    add_enum "google.events.firebase.remoteconfig.v1.RemoteConfigUpdateOrigin" do
      value :REMOTE_CONFIG_UPDATE_ORIGIN_UNSPECIFIED, 0
      value :CONSOLE, 1
      value :REST_API, 2
      value :ADMIN_SDK_NODE, 3
    end
    add_enum "google.events.firebase.remoteconfig.v1.RemoteConfigUpdateType" do
      value :REMOTE_CONFIG_UPDATE_TYPE_UNSPECIFIED, 0
      value :INCREMENTAL_UPDATE, 1
      value :FORCED_UPDATE, 2
      value :ROLLBACK, 3
    end
  end
end

module Google
  module Events
    module Firebase
      module RemoteConfig
        module V1
          RemoteConfigEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.remoteconfig.v1.RemoteConfigEventData").msgclass
          RemoteConfigUser = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.remoteconfig.v1.RemoteConfigUser").msgclass
          RemoteConfigUpdateOrigin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.remoteconfig.v1.RemoteConfigUpdateOrigin").enummodule
          RemoteConfigUpdateType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.remoteconfig.v1.RemoteConfigUpdateType").enummodule
        end
      end
    end
  end
end
