# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/remoteconfig/v1/events.proto

require 'google/protobuf'

require 'google/events/cloudevent_pb'
require 'google/events/firebase/remoteconfig/v1/data_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/firebase/remoteconfig/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.firebase.remoteconfig.v1.RemoteConfigUpdatedEvent" do
      optional :data, :message, 1, "google.events.firebase.remoteconfig.v1.RemoteConfigEventData"
    end
  end
end

module Google
  module Events
    module Firebase
      module RemoteConfig
        module V1
          RemoteConfigUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.remoteconfig.v1.RemoteConfigUpdatedEvent").msgclass
        end
      end
    end
  end
end
