# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/dataflow/v1beta3/events.proto

require 'google/protobuf'

require 'google/events/cloud/dataflow/v1beta3/data_pb'
require 'google/events/cloudevent_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/dataflow/v1beta3/events.proto", :syntax => :proto3) do
    add_message "google.events.cloud.dataflow.v1beta3.JobStatusChangedEvent" do
      optional :data, :message, 1, "google.events.cloud.dataflow.v1beta3.JobEventData"
    end
  end
end

module Google
  module Events
    module Cloud
      module Dataflow
        module V1beta3
          JobStatusChangedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.dataflow.v1beta3.JobStatusChangedEvent").msgclass
        end
      end
    end
  end
end
