# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/functions/v2/data.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/functions/v2/data.proto", :syntax => :proto3) do
    add_message "google.events.cloud.functions.v2.Function" do
      optional :name, :string, 1
      optional :environment, :enum, 10, "google.events.cloud.functions.v2.Environment"
      optional :description, :string, 2
      optional :build_config, :message, 3, "google.events.cloud.functions.v2.BuildConfig"
      optional :service_config, :message, 4, "google.events.cloud.functions.v2.ServiceConfig"
      optional :event_trigger, :message, 5, "google.events.cloud.functions.v2.EventTrigger"
      optional :state, :enum, 6, "google.events.cloud.functions.v2.Function.State"
      optional :update_time, :message, 7, "google.protobuf.Timestamp"
      map :labels, :string, :string, 8
      repeated :state_messages, :message, 9, "google.events.cloud.functions.v2.StateMessage"
    end
    add_enum "google.events.cloud.functions.v2.Function.State" do
      value :STATE_UNSPECIFIED, 0
      value :ACTIVE, 1
      value :FAILED, 2
      value :DEPLOYING, 3
      value :DELETING, 4
      value :UNKNOWN, 5
    end
    add_message "google.events.cloud.functions.v2.StateMessage" do
      optional :severity, :enum, 1, "google.events.cloud.functions.v2.StateMessage.Severity"
      optional :type, :string, 2
      optional :message, :string, 3
    end
    add_enum "google.events.cloud.functions.v2.StateMessage.Severity" do
      value :SEVERITY_UNSPECIFIED, 0
      value :ERROR, 1
      value :WARNING, 2
      value :INFO, 3
    end
    add_message "google.events.cloud.functions.v2.StorageSource" do
      optional :bucket, :string, 1
      optional :object, :string, 2
      optional :generation, :int64, 3
    end
    add_message "google.events.cloud.functions.v2.RepoSource" do
      optional :project_id, :string, 1
      optional :repo_name, :string, 2
      optional :dir, :string, 6
      optional :invert_regex, :bool, 7
      oneof :revision do
        optional :branch_name, :string, 3
        optional :tag_name, :string, 4
        optional :commit_sha, :string, 5
      end
    end
    add_message "google.events.cloud.functions.v2.Source" do
      oneof :source do
        optional :storage_source, :message, 1, "google.events.cloud.functions.v2.StorageSource"
        optional :repo_source, :message, 2, "google.events.cloud.functions.v2.RepoSource"
      end
    end
    add_message "google.events.cloud.functions.v2.SourceProvenance" do
      optional :resolved_storage_source, :message, 1, "google.events.cloud.functions.v2.StorageSource"
      optional :resolved_repo_source, :message, 2, "google.events.cloud.functions.v2.RepoSource"
    end
    add_message "google.events.cloud.functions.v2.BuildConfig" do
      optional :build, :string, 1
      optional :runtime, :string, 2
      optional :entry_point, :string, 3
      optional :source, :message, 4, "google.events.cloud.functions.v2.Source"
      optional :source_provenance, :message, 8, "google.events.cloud.functions.v2.SourceProvenance"
      optional :worker_pool, :string, 5
      map :environment_variables, :string, :string, 6
      optional :docker_registry, :enum, 10, "google.events.cloud.functions.v2.BuildConfig.DockerRegistry"
      optional :docker_repository, :string, 7
      optional :buildpack_stack, :string, 9
    end
    add_enum "google.events.cloud.functions.v2.BuildConfig.DockerRegistry" do
      value :DOCKER_REGISTRY_UNSPECIFIED, 0
      value :CONTAINER_REGISTRY, 1
      value :ARTIFACT_REGISTRY, 2
    end
    add_message "google.events.cloud.functions.v2.ServiceConfig" do
      optional :service, :string, 1
      optional :timeout_seconds, :int32, 2
      optional :available_memory, :string, 13
      optional :available_cpu, :string, 22
      map :environment_variables, :string, :string, 4
      optional :max_instance_count, :int32, 5
      optional :min_instance_count, :int32, 12
      optional :vpc_connector, :string, 6
      optional :vpc_connector_egress_settings, :enum, 7, "google.events.cloud.functions.v2.ServiceConfig.VpcConnectorEgressSettings"
      optional :ingress_settings, :enum, 8, "google.events.cloud.functions.v2.ServiceConfig.IngressSettings"
      optional :uri, :string, 9
      optional :service_account_email, :string, 10
      optional :all_traffic_on_latest_revision, :bool, 16
      repeated :secret_environment_variables, :message, 17, "google.events.cloud.functions.v2.SecretEnvVar"
      repeated :secret_volumes, :message, 19, "google.events.cloud.functions.v2.SecretVolume"
      optional :revision, :string, 18
      optional :max_instance_request_concurrency, :int32, 20
      optional :security_level, :enum, 21, "google.events.cloud.functions.v2.ServiceConfig.SecurityLevel"
    end
    add_enum "google.events.cloud.functions.v2.ServiceConfig.VpcConnectorEgressSettings" do
      value :VPC_CONNECTOR_EGRESS_SETTINGS_UNSPECIFIED, 0
      value :PRIVATE_RANGES_ONLY, 1
      value :ALL_TRAFFIC, 2
    end
    add_enum "google.events.cloud.functions.v2.ServiceConfig.IngressSettings" do
      value :INGRESS_SETTINGS_UNSPECIFIED, 0
      value :ALLOW_ALL, 1
      value :ALLOW_INTERNAL_ONLY, 2
      value :ALLOW_INTERNAL_AND_GCLB, 3
    end
    add_enum "google.events.cloud.functions.v2.ServiceConfig.SecurityLevel" do
      value :SECURITY_LEVEL_UNSPECIFIED, 0
      value :SECURE_ALWAYS, 1
      value :SECURE_OPTIONAL, 2
    end
    add_message "google.events.cloud.functions.v2.SecretEnvVar" do
      optional :key, :string, 1
      optional :project_id, :string, 2
      optional :secret, :string, 3
      optional :version, :string, 4
    end
    add_message "google.events.cloud.functions.v2.SecretVolume" do
      optional :mount_path, :string, 1
      optional :project_id, :string, 2
      optional :secret, :string, 3
      repeated :versions, :message, 4, "google.events.cloud.functions.v2.SecretVolume.SecretVersion"
    end
    add_message "google.events.cloud.functions.v2.SecretVolume.SecretVersion" do
      optional :version, :string, 1
      optional :path, :string, 2
    end
    add_message "google.events.cloud.functions.v2.EventTrigger" do
      optional :trigger, :string, 1
      optional :trigger_region, :string, 2
      optional :event_type, :string, 3
      repeated :event_filters, :message, 4, "google.events.cloud.functions.v2.EventFilter"
      optional :pubsub_topic, :string, 5
      optional :service_account_email, :string, 6
      optional :retry_policy, :enum, 7, "google.events.cloud.functions.v2.EventTrigger.RetryPolicy"
      optional :channel, :string, 8
    end
    add_enum "google.events.cloud.functions.v2.EventTrigger.RetryPolicy" do
      value :RETRY_POLICY_UNSPECIFIED, 0
      value :RETRY_POLICY_DO_NOT_RETRY, 1
      value :RETRY_POLICY_RETRY, 2
    end
    add_message "google.events.cloud.functions.v2.EventFilter" do
      optional :attribute, :string, 1
      optional :value, :string, 2
      optional :operator, :string, 3
    end
    add_message "google.events.cloud.functions.v2.FunctionEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.functions.v2.Function"
    end
    add_enum "google.events.cloud.functions.v2.Environment" do
      value :ENVIRONMENT_UNSPECIFIED, 0
      value :GEN_1, 1
      value :GEN_2, 2
    end
  end
end

module Google
  module Events
    module Cloud
      module Functions
        module V2
          Function = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.Function").msgclass
          Function::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.Function.State").enummodule
          StateMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.StateMessage").msgclass
          StateMessage::Severity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.StateMessage.Severity").enummodule
          StorageSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.StorageSource").msgclass
          RepoSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.RepoSource").msgclass
          Source = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.Source").msgclass
          SourceProvenance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.SourceProvenance").msgclass
          BuildConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.BuildConfig").msgclass
          BuildConfig::DockerRegistry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.BuildConfig.DockerRegistry").enummodule
          ServiceConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.ServiceConfig").msgclass
          ServiceConfig::VpcConnectorEgressSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.ServiceConfig.VpcConnectorEgressSettings").enummodule
          ServiceConfig::IngressSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.ServiceConfig.IngressSettings").enummodule
          ServiceConfig::SecurityLevel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.ServiceConfig.SecurityLevel").enummodule
          SecretEnvVar = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.SecretEnvVar").msgclass
          SecretVolume = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.SecretVolume").msgclass
          SecretVolume::SecretVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.SecretVolume.SecretVersion").msgclass
          EventTrigger = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.EventTrigger").msgclass
          EventTrigger::RetryPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.EventTrigger.RetryPolicy").enummodule
          EventFilter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.EventFilter").msgclass
          FunctionEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.FunctionEventData").msgclass
          Environment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.Environment").enummodule
        end
      end
    end
  end
end
