# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/functions/v2/events.proto

require 'google/protobuf'

require 'google/events/cloud/functions/v2/data_pb'
require 'google/events/cloudevent_pb'


descriptor_data = "\n-google/events/cloud/functions/v2/events.proto\x12 google.events.cloud.functions.v2\x1a+google/events/cloud/functions/v2/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\x97\x01\n\x14\x46unctionCreatedEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.functions.v2.FunctionEventData:<\xb2\xf8\xd8,*google.cloud.functions.function.v2.created\xca\xf8\xd8,\x08\x66unction\"\x97\x01\n\x14\x46unctionUpdatedEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.functions.v2.FunctionEventData:<\xb2\xf8\xd8,*google.cloud.functions.function.v2.updated\xca\xf8\xd8,\x08\x66unction\"\x97\x01\n\x14\x46unctionDeletedEvent\x12\x41\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x33.google.events.cloud.functions.v2.FunctionEventData:<\xb2\xf8\xd8,*google.cloud.functions.function.v2.deleted\xca\xf8\xd8,\x08\x66unctionB\xd0\x01\xaa\x02)Google.Events.Protobuf.Cloud.Functions.V2\xca\x02 Google\\Events\\Cloud\\Functions\\V2\xea\x02$Google::Events::Cloud::Functions::V2\xba\xf8\xd8,\x0f\x43loud Functions\xc2\xf8\xd8,A\n\x08\x66unction\x12\x35The resource ID of the Function triggering the event.b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.events.cloud.functions.v2.FunctionEventData", "google/events/cloud/functions/v2/data.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Events
    module Cloud
      module Functions
        module V2
          FunctionCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.FunctionCreatedEvent").msgclass
          FunctionUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.FunctionUpdatedEvent").msgclass
          FunctionDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.FunctionDeletedEvent").msgclass
        end
      end
    end
  end
end
