# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/functions/v2/events.proto

require 'google/protobuf'

require 'google/events/cloud/functions/v2/data_pb'
require 'google/events/cloudevent_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/functions/v2/events.proto", :syntax => :proto3) do
    add_message "google.events.cloud.functions.v2.FunctionCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.functions.v2.FunctionEventData"
    end
    add_message "google.events.cloud.functions.v2.FunctionUpdatedEvent" do
      optional :data, :message, 1, "google.events.cloud.functions.v2.FunctionEventData"
    end
    add_message "google.events.cloud.functions.v2.FunctionDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.functions.v2.FunctionEventData"
    end
  end
end

module Google
  module Events
    module Cloud
      module Functions
        module V2
          FunctionCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.FunctionCreatedEvent").msgclass
          FunctionUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.FunctionUpdatedEvent").msgclass
          FunctionDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.functions.v2.FunctionDeletedEvent").msgclass
        end
      end
    end
  end
end
