# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/datastream/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/duration_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/datastream/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.cloud.datastream.v1.OracleProfile" do
      optional :hostname, :string, 1
      optional :port, :int32, 2
      optional :username, :string, 3
      optional :database_service, :string, 5
      map :connection_attributes, :string, :string, 6
    end
    add_message "google.events.cloud.datastream.v1.MysqlProfile" do
      optional :hostname, :string, 1
      optional :port, :int32, 2
      optional :username, :string, 3
      optional :ssl_config, :message, 5, "google.events.cloud.datastream.v1.MysqlSslConfig"
    end
    add_message "google.events.cloud.datastream.v1.PostgresqlProfile" do
      optional :hostname, :string, 1
      optional :port, :int32, 2
      optional :username, :string, 3
      optional :database, :string, 5
    end
    add_message "google.events.cloud.datastream.v1.GcsProfile" do
      optional :bucket, :string, 1
      optional :root_path, :string, 2
    end
    add_message "google.events.cloud.datastream.v1.BigQueryProfile" do
    end
    add_message "google.events.cloud.datastream.v1.StaticServiceIpConnectivity" do
    end
    add_message "google.events.cloud.datastream.v1.ForwardSshTunnelConnectivity" do
      optional :hostname, :string, 1
      optional :username, :string, 2
      optional :port, :int32, 3
    end
    add_message "google.events.cloud.datastream.v1.VpcPeeringConfig" do
      optional :vpc, :string, 1
      optional :subnet, :string, 2
    end
    add_message "google.events.cloud.datastream.v1.PrivateConnection" do
      optional :name, :string, 1
      optional :create_time, :message, 2, "google.protobuf.Timestamp"
      optional :update_time, :message, 3, "google.protobuf.Timestamp"
      map :labels, :string, :string, 4
      optional :display_name, :string, 5
      optional :state, :enum, 6, "google.events.cloud.datastream.v1.PrivateConnection.State"
      optional :error, :message, 7, "google.events.cloud.datastream.v1.Error"
      optional :vpc_peering_config, :message, 100, "google.events.cloud.datastream.v1.VpcPeeringConfig"
    end
    add_enum "google.events.cloud.datastream.v1.PrivateConnection.State" do
      value :STATE_UNSPECIFIED, 0
      value :CREATING, 1
      value :CREATED, 2
      value :FAILED, 3
      value :DELETING, 4
      value :FAILED_TO_DELETE, 5
    end
    add_message "google.events.cloud.datastream.v1.PrivateConnectivity" do
      optional :private_connection, :string, 1
    end
    add_message "google.events.cloud.datastream.v1.Route" do
      optional :name, :string, 1
      optional :create_time, :message, 2, "google.protobuf.Timestamp"
      optional :update_time, :message, 3, "google.protobuf.Timestamp"
      map :labels, :string, :string, 4
      optional :display_name, :string, 5
      optional :destination_address, :string, 6
      optional :destination_port, :int32, 7
    end
    add_message "google.events.cloud.datastream.v1.MysqlSslConfig" do
      optional :client_key_set, :bool, 2
      optional :client_certificate_set, :bool, 4
      optional :ca_certificate_set, :bool, 6
    end
    add_message "google.events.cloud.datastream.v1.ConnectionProfile" do
      optional :name, :string, 1
      optional :create_time, :message, 2, "google.protobuf.Timestamp"
      optional :update_time, :message, 3, "google.protobuf.Timestamp"
      map :labels, :string, :string, 4
      optional :display_name, :string, 5
      oneof :profile do
        optional :oracle_profile, :message, 100, "google.events.cloud.datastream.v1.OracleProfile"
        optional :gcs_profile, :message, 101, "google.events.cloud.datastream.v1.GcsProfile"
        optional :mysql_profile, :message, 102, "google.events.cloud.datastream.v1.MysqlProfile"
        optional :bigquery_profile, :message, 103, "google.events.cloud.datastream.v1.BigQueryProfile"
        optional :postgresql_profile, :message, 104, "google.events.cloud.datastream.v1.PostgresqlProfile"
      end
      oneof :connectivity do
        optional :static_service_ip_connectivity, :message, 200, "google.events.cloud.datastream.v1.StaticServiceIpConnectivity"
        optional :forward_ssh_connectivity, :message, 201, "google.events.cloud.datastream.v1.ForwardSshTunnelConnectivity"
        optional :private_connectivity, :message, 202, "google.events.cloud.datastream.v1.PrivateConnectivity"
      end
    end
    add_message "google.events.cloud.datastream.v1.OracleColumn" do
      optional :column, :string, 1
      optional :data_type, :string, 2
      optional :length, :int32, 3
      optional :precision, :int32, 4
      optional :scale, :int32, 5
      optional :encoding, :string, 6
      optional :primary_key, :bool, 7
      optional :nullable, :bool, 8
      optional :ordinal_position, :int32, 9
    end
    add_message "google.events.cloud.datastream.v1.OracleTable" do
      optional :table, :string, 1
      repeated :oracle_columns, :message, 2, "google.events.cloud.datastream.v1.OracleColumn"
    end
    add_message "google.events.cloud.datastream.v1.OracleSchema" do
      optional :schema, :string, 1
      repeated :oracle_tables, :message, 2, "google.events.cloud.datastream.v1.OracleTable"
    end
    add_message "google.events.cloud.datastream.v1.OracleRdbms" do
      repeated :oracle_schemas, :message, 1, "google.events.cloud.datastream.v1.OracleSchema"
    end
    add_message "google.events.cloud.datastream.v1.OracleSourceConfig" do
      optional :include_objects, :message, 1, "google.events.cloud.datastream.v1.OracleRdbms"
      optional :exclude_objects, :message, 2, "google.events.cloud.datastream.v1.OracleRdbms"
      optional :max_concurrent_cdc_tasks, :int32, 3
      oneof :large_objects_handling do
        optional :drop_large_objects, :message, 100, "google.events.cloud.datastream.v1.OracleSourceConfig.DropLargeObjects"
        optional :stream_large_objects, :message, 102, "google.events.cloud.datastream.v1.OracleSourceConfig.StreamLargeObjects"
      end
    end
    add_message "google.events.cloud.datastream.v1.OracleSourceConfig.DropLargeObjects" do
    end
    add_message "google.events.cloud.datastream.v1.OracleSourceConfig.StreamLargeObjects" do
    end
    add_message "google.events.cloud.datastream.v1.PostgresqlColumn" do
      optional :column, :string, 1
      optional :data_type, :string, 2
      optional :length, :int32, 3
      optional :precision, :int32, 4
      optional :scale, :int32, 5
      optional :primary_key, :bool, 7
      optional :nullable, :bool, 8
      optional :ordinal_position, :int32, 9
    end
    add_message "google.events.cloud.datastream.v1.PostgresqlTable" do
      optional :table, :string, 1
      repeated :postgresql_columns, :message, 2, "google.events.cloud.datastream.v1.PostgresqlColumn"
    end
    add_message "google.events.cloud.datastream.v1.PostgresqlSchema" do
      optional :schema, :string, 1
      repeated :postgresql_tables, :message, 2, "google.events.cloud.datastream.v1.PostgresqlTable"
    end
    add_message "google.events.cloud.datastream.v1.PostgresqlRdbms" do
      repeated :postgresql_schemas, :message, 1, "google.events.cloud.datastream.v1.PostgresqlSchema"
    end
    add_message "google.events.cloud.datastream.v1.PostgresqlSourceConfig" do
      optional :include_objects, :message, 1, "google.events.cloud.datastream.v1.PostgresqlRdbms"
      optional :exclude_objects, :message, 2, "google.events.cloud.datastream.v1.PostgresqlRdbms"
      optional :replication_slot, :string, 3
      optional :publication, :string, 4
    end
    add_message "google.events.cloud.datastream.v1.MysqlColumn" do
      optional :column, :string, 1
      optional :data_type, :string, 2
      optional :length, :int32, 3
      optional :collation, :string, 4
      optional :primary_key, :bool, 5
      optional :nullable, :bool, 6
      optional :ordinal_position, :int32, 7
    end
    add_message "google.events.cloud.datastream.v1.MysqlTable" do
      optional :table, :string, 1
      repeated :mysql_columns, :message, 2, "google.events.cloud.datastream.v1.MysqlColumn"
    end
    add_message "google.events.cloud.datastream.v1.MysqlDatabase" do
      optional :database, :string, 1
      repeated :mysql_tables, :message, 2, "google.events.cloud.datastream.v1.MysqlTable"
    end
    add_message "google.events.cloud.datastream.v1.MysqlRdbms" do
      repeated :mysql_databases, :message, 1, "google.events.cloud.datastream.v1.MysqlDatabase"
    end
    add_message "google.events.cloud.datastream.v1.MysqlSourceConfig" do
      optional :include_objects, :message, 1, "google.events.cloud.datastream.v1.MysqlRdbms"
      optional :exclude_objects, :message, 2, "google.events.cloud.datastream.v1.MysqlRdbms"
      optional :max_concurrent_cdc_tasks, :int32, 3
    end
    add_message "google.events.cloud.datastream.v1.SourceConfig" do
      optional :source_connection_profile, :string, 1
      oneof :source_stream_config do
        optional :oracle_source_config, :message, 100, "google.events.cloud.datastream.v1.OracleSourceConfig"
        optional :mysql_source_config, :message, 101, "google.events.cloud.datastream.v1.MysqlSourceConfig"
        optional :postgresql_source_config, :message, 102, "google.events.cloud.datastream.v1.PostgresqlSourceConfig"
      end
    end
    add_message "google.events.cloud.datastream.v1.AvroFileFormat" do
    end
    add_message "google.events.cloud.datastream.v1.JsonFileFormat" do
      optional :schema_file_format, :enum, 1, "google.events.cloud.datastream.v1.JsonFileFormat.SchemaFileFormat"
      optional :compression, :enum, 2, "google.events.cloud.datastream.v1.JsonFileFormat.JsonCompression"
    end
    add_enum "google.events.cloud.datastream.v1.JsonFileFormat.SchemaFileFormat" do
      value :SCHEMA_FILE_FORMAT_UNSPECIFIED, 0
      value :NO_SCHEMA_FILE, 1
      value :AVRO_SCHEMA_FILE, 2
    end
    add_enum "google.events.cloud.datastream.v1.JsonFileFormat.JsonCompression" do
      value :JSON_COMPRESSION_UNSPECIFIED, 0
      value :NO_COMPRESSION, 1
      value :GZIP, 2
    end
    add_message "google.events.cloud.datastream.v1.GcsDestinationConfig" do
      optional :path, :string, 1
      optional :file_rotation_mb, :int32, 2
      optional :file_rotation_interval, :message, 3, "google.protobuf.Duration"
      oneof :file_format do
        optional :avro_file_format, :message, 100, "google.events.cloud.datastream.v1.AvroFileFormat"
        optional :json_file_format, :message, 101, "google.events.cloud.datastream.v1.JsonFileFormat"
      end
    end
    add_message "google.events.cloud.datastream.v1.BigQueryDestinationConfig" do
      optional :data_freshness, :message, 300, "google.protobuf.Duration"
      oneof :dataset_config do
        optional :single_target_dataset, :message, 201, "google.events.cloud.datastream.v1.BigQueryDestinationConfig.SingleTargetDataset"
        optional :source_hierarchy_datasets, :message, 202, "google.events.cloud.datastream.v1.BigQueryDestinationConfig.SourceHierarchyDatasets"
      end
    end
    add_message "google.events.cloud.datastream.v1.BigQueryDestinationConfig.SingleTargetDataset" do
      optional :dataset_id, :string, 1
    end
    add_message "google.events.cloud.datastream.v1.BigQueryDestinationConfig.SourceHierarchyDatasets" do
      optional :dataset_template, :message, 2, "google.events.cloud.datastream.v1.BigQueryDestinationConfig.SourceHierarchyDatasets.DatasetTemplate"
    end
    add_message "google.events.cloud.datastream.v1.BigQueryDestinationConfig.SourceHierarchyDatasets.DatasetTemplate" do
      optional :location, :string, 1
      optional :dataset_id_prefix, :string, 2
      optional :kms_key_name, :string, 3
    end
    add_message "google.events.cloud.datastream.v1.DestinationConfig" do
      optional :destination_connection_profile, :string, 1
      oneof :destination_stream_config do
        optional :gcs_destination_config, :message, 100, "google.events.cloud.datastream.v1.GcsDestinationConfig"
        optional :bigquery_destination_config, :message, 101, "google.events.cloud.datastream.v1.BigQueryDestinationConfig"
      end
    end
    add_message "google.events.cloud.datastream.v1.Stream" do
      optional :name, :string, 1
      optional :create_time, :message, 2, "google.protobuf.Timestamp"
      optional :update_time, :message, 3, "google.protobuf.Timestamp"
      map :labels, :string, :string, 4
      optional :display_name, :string, 5
      optional :source_config, :message, 6, "google.events.cloud.datastream.v1.SourceConfig"
      optional :destination_config, :message, 7, "google.events.cloud.datastream.v1.DestinationConfig"
      optional :state, :enum, 8, "google.events.cloud.datastream.v1.Stream.State"
      repeated :errors, :message, 9, "google.events.cloud.datastream.v1.Error"
      proto3_optional :customer_managed_encryption_key, :string, 10
      oneof :backfill_strategy do
        optional :backfill_all, :message, 101, "google.events.cloud.datastream.v1.Stream.BackfillAllStrategy"
        optional :backfill_none, :message, 102, "google.events.cloud.datastream.v1.Stream.BackfillNoneStrategy"
      end
    end
    add_message "google.events.cloud.datastream.v1.Stream.BackfillAllStrategy" do
      oneof :excluded_objects do
        optional :oracle_excluded_objects, :message, 1, "google.events.cloud.datastream.v1.OracleRdbms"
        optional :mysql_excluded_objects, :message, 2, "google.events.cloud.datastream.v1.MysqlRdbms"
        optional :postgresql_excluded_objects, :message, 3, "google.events.cloud.datastream.v1.PostgresqlRdbms"
      end
    end
    add_message "google.events.cloud.datastream.v1.Stream.BackfillNoneStrategy" do
    end
    add_enum "google.events.cloud.datastream.v1.Stream.State" do
      value :STATE_UNSPECIFIED, 0
      value :NOT_STARTED, 1
      value :RUNNING, 2
      value :PAUSED, 3
      value :MAINTENANCE, 4
      value :FAILED, 5
      value :FAILED_PERMANENTLY, 6
      value :STARTING, 7
      value :DRAINING, 8
    end
    add_message "google.events.cloud.datastream.v1.Error" do
      optional :reason, :string, 1
      optional :error_uuid, :string, 2
      optional :message, :string, 3
      optional :error_time, :message, 4, "google.protobuf.Timestamp"
      map :details, :string, :string, 5
    end
    add_message "google.events.cloud.datastream.v1.ConnectionProfileEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.datastream.v1.ConnectionProfile"
    end
    add_message "google.events.cloud.datastream.v1.PrivateConnectionEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.datastream.v1.PrivateConnection"
    end
    add_message "google.events.cloud.datastream.v1.StreamEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.datastream.v1.Stream"
    end
    add_message "google.events.cloud.datastream.v1.RouteEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.datastream.v1.Route"
    end
  end
end

module Google
  module Events
    module Cloud
      module Datastream
        module V1
          OracleProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.OracleProfile").msgclass
          MysqlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.MysqlProfile").msgclass
          PostgresqlProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PostgresqlProfile").msgclass
          GcsProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.GcsProfile").msgclass
          BigQueryProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.BigQueryProfile").msgclass
          StaticServiceIpConnectivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.StaticServiceIpConnectivity").msgclass
          ForwardSshTunnelConnectivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.ForwardSshTunnelConnectivity").msgclass
          VpcPeeringConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.VpcPeeringConfig").msgclass
          PrivateConnection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PrivateConnection").msgclass
          PrivateConnection::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PrivateConnection.State").enummodule
          PrivateConnectivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PrivateConnectivity").msgclass
          Route = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.Route").msgclass
          MysqlSslConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.MysqlSslConfig").msgclass
          ConnectionProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.ConnectionProfile").msgclass
          OracleColumn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.OracleColumn").msgclass
          OracleTable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.OracleTable").msgclass
          OracleSchema = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.OracleSchema").msgclass
          OracleRdbms = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.OracleRdbms").msgclass
          OracleSourceConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.OracleSourceConfig").msgclass
          OracleSourceConfig::DropLargeObjects = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.OracleSourceConfig.DropLargeObjects").msgclass
          OracleSourceConfig::StreamLargeObjects = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.OracleSourceConfig.StreamLargeObjects").msgclass
          PostgresqlColumn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PostgresqlColumn").msgclass
          PostgresqlTable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PostgresqlTable").msgclass
          PostgresqlSchema = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PostgresqlSchema").msgclass
          PostgresqlRdbms = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PostgresqlRdbms").msgclass
          PostgresqlSourceConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PostgresqlSourceConfig").msgclass
          MysqlColumn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.MysqlColumn").msgclass
          MysqlTable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.MysqlTable").msgclass
          MysqlDatabase = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.MysqlDatabase").msgclass
          MysqlRdbms = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.MysqlRdbms").msgclass
          MysqlSourceConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.MysqlSourceConfig").msgclass
          SourceConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.SourceConfig").msgclass
          AvroFileFormat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.AvroFileFormat").msgclass
          JsonFileFormat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.JsonFileFormat").msgclass
          JsonFileFormat::SchemaFileFormat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.JsonFileFormat.SchemaFileFormat").enummodule
          JsonFileFormat::JsonCompression = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.JsonFileFormat.JsonCompression").enummodule
          GcsDestinationConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.GcsDestinationConfig").msgclass
          BigQueryDestinationConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.BigQueryDestinationConfig").msgclass
          BigQueryDestinationConfig::SingleTargetDataset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.BigQueryDestinationConfig.SingleTargetDataset").msgclass
          BigQueryDestinationConfig::SourceHierarchyDatasets = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.BigQueryDestinationConfig.SourceHierarchyDatasets").msgclass
          BigQueryDestinationConfig::SourceHierarchyDatasets::DatasetTemplate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.BigQueryDestinationConfig.SourceHierarchyDatasets.DatasetTemplate").msgclass
          DestinationConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.DestinationConfig").msgclass
          Stream = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.Stream").msgclass
          Stream::BackfillAllStrategy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.Stream.BackfillAllStrategy").msgclass
          Stream::BackfillNoneStrategy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.Stream.BackfillNoneStrategy").msgclass
          Stream::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.Stream.State").enummodule
          Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.Error").msgclass
          ConnectionProfileEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.ConnectionProfileEventData").msgclass
          PrivateConnectionEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PrivateConnectionEventData").msgclass
          StreamEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.StreamEventData").msgclass
          RouteEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.RouteEventData").msgclass
        end
      end
    end
  end
end
