# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/datastream/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/datastream/v1/data_pb'
require 'google/events/cloudevent_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/datastream/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.cloud.datastream.v1.ConnectionProfileCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.datastream.v1.ConnectionProfileEventData"
    end
    add_message "google.events.cloud.datastream.v1.ConnectionProfileUpdatedEvent" do
      optional :data, :message, 1, "google.events.cloud.datastream.v1.ConnectionProfileEventData"
    end
    add_message "google.events.cloud.datastream.v1.ConnectionProfileDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.datastream.v1.ConnectionProfileEventData"
    end
    add_message "google.events.cloud.datastream.v1.StreamCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.datastream.v1.StreamEventData"
    end
    add_message "google.events.cloud.datastream.v1.StreamUpdatedEvent" do
      optional :data, :message, 1, "google.events.cloud.datastream.v1.StreamEventData"
    end
    add_message "google.events.cloud.datastream.v1.StreamDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.datastream.v1.StreamEventData"
    end
    add_message "google.events.cloud.datastream.v1.PrivateConnectionCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.datastream.v1.PrivateConnectionEventData"
    end
    add_message "google.events.cloud.datastream.v1.PrivateConnectionDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.datastream.v1.PrivateConnectionEventData"
    end
    add_message "google.events.cloud.datastream.v1.RouteCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.datastream.v1.RouteEventData"
    end
    add_message "google.events.cloud.datastream.v1.RouteDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.datastream.v1.RouteEventData"
    end
  end
end

module Google
  module Events
    module Cloud
      module Datastream
        module V1
          ConnectionProfileCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.ConnectionProfileCreatedEvent").msgclass
          ConnectionProfileUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.ConnectionProfileUpdatedEvent").msgclass
          ConnectionProfileDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.ConnectionProfileDeletedEvent").msgclass
          StreamCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.StreamCreatedEvent").msgclass
          StreamUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.StreamUpdatedEvent").msgclass
          StreamDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.StreamDeletedEvent").msgclass
          PrivateConnectionCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PrivateConnectionCreatedEvent").msgclass
          PrivateConnectionDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.PrivateConnectionDeletedEvent").msgclass
          RouteCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.RouteCreatedEvent").msgclass
          RouteDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.datastream.v1.RouteDeletedEvent").msgclass
        end
      end
    end
  end
end
