# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/firebasealerts/v1/cloud_event_payload.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/type/date_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/firebase/firebasealerts/v1/cloud_event_payload.proto", :syntax => :proto3) do
    add_message "google.events.firebase.firebasealerts.v1.CrashlyticsIssue" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :subtitle, :string, 3
      optional :app_version, :string, 4
    end
    add_message "google.events.firebase.firebasealerts.v1.CrashlyticsNewFatalIssuePayload" do
      optional :issue, :message, 1, "google.events.firebase.firebasealerts.v1.CrashlyticsIssue"
    end
    add_message "google.events.firebase.firebasealerts.v1.CrashlyticsNewNonfatalIssuePayload" do
      optional :issue, :message, 1, "google.events.firebase.firebasealerts.v1.CrashlyticsIssue"
    end
    add_message "google.events.firebase.firebasealerts.v1.CrashlyticsRegressionAlertPayload" do
      optional :type, :string, 1
      optional :issue, :message, 2, "google.events.firebase.firebasealerts.v1.CrashlyticsIssue"
      optional :resolve_time, :message, 3, "google.protobuf.Timestamp"
    end
    add_message "google.events.firebase.firebasealerts.v1.CrashlyticsVelocityAlertPayload" do
      optional :issue, :message, 1, "google.events.firebase.firebasealerts.v1.CrashlyticsIssue"
      optional :create_time, :message, 2, "google.protobuf.Timestamp"
      optional :crash_count, :int64, 3
      optional :crash_percentage, :double, 4
      optional :first_version, :string, 5
    end
    add_message "google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload" do
      optional :digest_date, :message, 5, "google.type.Date"
      repeated :trending_issues, :message, 6, "google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload.TrendingIssueDetails"
    end
    add_message "google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload.TrendingIssueDetails" do
      optional :type, :string, 1
      optional :issue, :message, 2, "google.events.firebase.firebasealerts.v1.CrashlyticsIssue"
      optional :event_count, :int64, 3
      optional :user_count, :int64, 4
    end
    add_message "google.events.firebase.firebasealerts.v1.CrashlyticsNewAnrIssuePayload" do
      optional :issue, :message, 1, "google.events.firebase.firebasealerts.v1.CrashlyticsIssue"
    end
    add_message "google.events.firebase.firebasealerts.v1.CrashlyticsMissingSymbolsPayload" do
      optional :app_version, :string, 1
      optional :uuid, :string, 2
    end
    add_message "google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload" do
      optional :event_name, :string, 1
      optional :event_type, :string, 2
      optional :metric_type, :string, 3
      optional :num_samples, :int64, 4
      optional :threshold_value, :float, 5
      optional :threshold_unit, :string, 6
      optional :condition_percentile, :int32, 7
      optional :app_version, :string, 8
      optional :violation_value, :float, 9
      optional :violation_unit, :string, 10
      optional :investigate_uri, :string, 11
    end
    add_message "google.events.firebase.firebasealerts.v1.AppDistroNewTesterIosDevicePayload" do
      optional :tester_name, :string, 1
      optional :tester_email, :string, 2
      optional :tester_device_model_name, :string, 3
      optional :tester_device_identifier, :string, 4
    end
    add_message "google.events.firebase.firebasealerts.v1.AppDistroInAppFeedbackPayload" do
      optional :feedback_report, :string, 1
      optional :feedback_console_uri, :string, 8
      optional :tester_name, :string, 2
      optional :tester_email, :string, 3
      optional :app_version, :string, 9
      optional :text, :string, 6
      optional :screenshot_uri, :string, 7
    end
    add_message "google.events.firebase.firebasealerts.v1.BillingPlanUpdatePayload" do
      optional :billing_plan, :string, 1
      optional :principal_email, :string, 2
      optional :notification_type, :string, 3
    end
    add_message "google.events.firebase.firebasealerts.v1.BillingPlanAutomatedUpdatePayload" do
      optional :billing_plan, :string, 1
      optional :notification_type, :string, 2
    end
  end
end

module Google
  module Events
    module Firebase
      module FirebaseAlerts
        module V1
          CrashlyticsIssue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.CrashlyticsIssue").msgclass
          CrashlyticsNewFatalIssuePayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.CrashlyticsNewFatalIssuePayload").msgclass
          CrashlyticsNewNonfatalIssuePayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.CrashlyticsNewNonfatalIssuePayload").msgclass
          CrashlyticsRegressionAlertPayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.CrashlyticsRegressionAlertPayload").msgclass
          CrashlyticsVelocityAlertPayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.CrashlyticsVelocityAlertPayload").msgclass
          CrashlyticsStabilityDigestPayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload").msgclass
          CrashlyticsStabilityDigestPayload::TrendingIssueDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.CrashlyticsStabilityDigestPayload.TrendingIssueDetails").msgclass
          CrashlyticsNewAnrIssuePayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.CrashlyticsNewAnrIssuePayload").msgclass
          CrashlyticsMissingSymbolsPayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.CrashlyticsMissingSymbolsPayload").msgclass
          FireperfThresholdAlertPayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.FireperfThresholdAlertPayload").msgclass
          AppDistroNewTesterIosDevicePayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.AppDistroNewTesterIosDevicePayload").msgclass
          AppDistroInAppFeedbackPayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.AppDistroInAppFeedbackPayload").msgclass
          BillingPlanUpdatePayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.BillingPlanUpdatePayload").msgclass
          BillingPlanAutomatedUpdatePayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.BillingPlanAutomatedUpdatePayload").msgclass
        end
      end
    end
  end
end
