# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/firebasealerts/v1/events.proto

require 'google/protobuf'

require 'google/events/cloudevent_pb'
require 'google/events/firebase/firebasealerts/v1/data_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/firebase/firebasealerts/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.firebase.firebasealerts.v1.AlertPublishedEvent" do
      optional :data, :message, 1, "google.events.firebase.firebasealerts.v1.AlertData"
    end
  end
end

module Google
  module Events
    module Firebase
      module FirebaseAlerts
        module V1
          AlertPublishedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.firebasealerts.v1.AlertPublishedEvent").msgclass
        end
      end
    end
  end
end
