# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/database/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'


descriptor_data = "\n-google/events/firebase/database/v1/data.proto\x12\"google.events.firebase.database.v1\x1a\x1cgoogle/protobuf/struct.proto\"a\n\x12ReferenceEventData\x12$\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Value\x12%\n\x05\x64\x65lta\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueB|\xaa\x02+Google.Events.Protobuf.Firebase.Database.V1\xca\x02\"Google\\Events\\Firebase\\Database\\V1\xea\x02&Google::Events::Firebase::Database::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.protobuf.Value", "google/protobuf/struct.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Events
    module Firebase
      module Database
        module V1
          ReferenceEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.database.v1.ReferenceEventData").msgclass
        end
      end
    end
  end
end
