# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/database/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/firebase/database/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.firebase.database.v1.ReferenceEventData" do
      optional :data, :message, 1, "google.protobuf.Value"
      optional :delta, :message, 2, "google.protobuf.Value"
    end
  end
end

module Google
  module Events
    module Firebase
      module Database
        module V1
          ReferenceEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.database.v1.ReferenceEventData").msgclass
        end
      end
    end
  end
end
