# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/database/v1/events.proto

require 'google/protobuf'

require 'google/events/cloudevent_pb'
require 'google/events/firebase/database/v1/data_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/firebase/database/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.firebase.database.v1.ReferenceCreatedEvent" do
      optional :data, :message, 1, "google.events.firebase.database.v1.ReferenceEventData"
    end
    add_message "google.events.firebase.database.v1.ReferenceUpdatedEvent" do
      optional :data, :message, 1, "google.events.firebase.database.v1.ReferenceEventData"
    end
    add_message "google.events.firebase.database.v1.ReferenceDeletedEvent" do
      optional :data, :message, 1, "google.events.firebase.database.v1.ReferenceEventData"
    end
    add_message "google.events.firebase.database.v1.ReferenceWrittenEvent" do
      optional :data, :message, 1, "google.events.firebase.database.v1.ReferenceEventData"
    end
  end
end

module Google
  module Events
    module Firebase
      module Database
        module V1
          ReferenceCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.database.v1.ReferenceCreatedEvent").msgclass
          ReferenceUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.database.v1.ReferenceUpdatedEvent").msgclass
          ReferenceDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.database.v1.ReferenceDeletedEvent").msgclass
          ReferenceWrittenEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.database.v1.ReferenceWrittenEvent").msgclass
        end
      end
    end
  end
end
