# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/beyondcorp/appconnectors/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/beyondcorp/appconnectors/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.cloud.beyondcorp.appconnectors.v1.ResourceInfo" do
      optional :id, :string, 1
      optional :status, :enum, 2, "google.events.cloud.beyondcorp.appconnectors.v1.HealthStatus"
      optional :time, :message, 4, "google.protobuf.Timestamp"
      repeated :sub, :message, 5, "google.events.cloud.beyondcorp.appconnectors.v1.ResourceInfo"
    end
    add_message "google.events.cloud.beyondcorp.appconnectors.v1.AppConnector" do
      optional :name, :string, 1
      optional :create_time, :message, 2, "google.protobuf.Timestamp"
      optional :update_time, :message, 3, "google.protobuf.Timestamp"
      map :labels, :string, :string, 4
      optional :display_name, :string, 5
      optional :uid, :string, 6
      optional :state, :enum, 7, "google.events.cloud.beyondcorp.appconnectors.v1.AppConnector.State"
      optional :principal_info, :message, 8, "google.events.cloud.beyondcorp.appconnectors.v1.AppConnector.PrincipalInfo"
      optional :resource_info, :message, 11, "google.events.cloud.beyondcorp.appconnectors.v1.ResourceInfo"
    end
    add_message "google.events.cloud.beyondcorp.appconnectors.v1.AppConnector.PrincipalInfo" do
      oneof :type do
        optional :service_account, :message, 1, "google.events.cloud.beyondcorp.appconnectors.v1.AppConnector.PrincipalInfo.ServiceAccount"
      end
    end
    add_message "google.events.cloud.beyondcorp.appconnectors.v1.AppConnector.PrincipalInfo.ServiceAccount" do
      optional :email, :string, 1
    end
    add_enum "google.events.cloud.beyondcorp.appconnectors.v1.AppConnector.State" do
      value :STATE_UNSPECIFIED, 0
      value :CREATING, 1
      value :CREATED, 2
      value :UPDATING, 3
      value :DELETING, 4
      value :DOWN, 5
    end
    add_message "google.events.cloud.beyondcorp.appconnectors.v1.AppConnectorEventData" do
      proto3_optional :payload, :message, 1, "google.events.cloud.beyondcorp.appconnectors.v1.AppConnector"
    end
    add_enum "google.events.cloud.beyondcorp.appconnectors.v1.HealthStatus" do
      value :HEALTH_STATUS_UNSPECIFIED, 0
      value :HEALTHY, 1
      value :UNHEALTHY, 2
      value :UNRESPONSIVE, 3
      value :DEGRADED, 4
    end
  end
end

module Google
  module Events
    module Cloud
      module BeyondCorp
        module AppConnectors
          module V1
            ResourceInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnectors.v1.ResourceInfo").msgclass
            AppConnector = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnectors.v1.AppConnector").msgclass
            AppConnector::PrincipalInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnectors.v1.AppConnector.PrincipalInfo").msgclass
            AppConnector::PrincipalInfo::ServiceAccount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnectors.v1.AppConnector.PrincipalInfo.ServiceAccount").msgclass
            AppConnector::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnectors.v1.AppConnector.State").enummodule
            AppConnectorEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnectors.v1.AppConnectorEventData").msgclass
            HealthStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.beyondcorp.appconnectors.v1.HealthStatus").enummodule
          end
        end
      end
    end
  end
end
