# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/storage/v1/data.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/storage/v1/data.proto", :syntax => :proto3) do
    add_message "google.events.cloud.storage.v1.StorageObjectData" do
      optional :content_encoding, :string, 1
      optional :content_disposition, :string, 2
      optional :cache_control, :string, 3
      optional :content_language, :string, 5
      optional :metageneration, :int64, 6
      optional :time_deleted, :message, 7, "google.protobuf.Timestamp"
      optional :content_type, :string, 8
      optional :size, :int64, 9
      optional :time_created, :message, 10, "google.protobuf.Timestamp"
      optional :crc32c, :string, 11
      optional :component_count, :int32, 12
      optional :md5_hash, :string, 13
      optional :etag, :string, 14
      optional :updated, :message, 15, "google.protobuf.Timestamp"
      optional :storage_class, :string, 16
      optional :kms_key_name, :string, 17
      optional :time_storage_class_updated, :message, 18, "google.protobuf.Timestamp"
      optional :temporary_hold, :bool, 19
      optional :retention_expiration_time, :message, 20, "google.protobuf.Timestamp"
      map :metadata, :string, :string, 21
      optional :event_based_hold, :bool, 29
      optional :name, :string, 23
      optional :id, :string, 24
      optional :bucket, :string, 25
      optional :generation, :int64, 26
      optional :customer_encryption, :message, 28, "google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption"
      optional :media_link, :string, 100
      optional :self_link, :string, 101
    end
    add_message "google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption" do
      optional :encryption_algorithm, :string, 1
      optional :key_sha256, :string, 2
    end
  end
end

module Google
  module Events
    module Cloud
      module Storage
        module V1
          StorageObjectData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.storage.v1.StorageObjectData").msgclass
          StorageObjectData::CustomerEncryption = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption").msgclass
        end
      end
    end
  end
end
