# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/memcache/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/memcache/v1/data_pb'
require 'google/events/cloudevent_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/cloud/memcache/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.cloud.memcache.v1.InstanceCreatedEvent" do
      optional :data, :message, 1, "google.events.cloud.memcache.v1.InstanceEventData"
    end
    add_message "google.events.cloud.memcache.v1.InstanceUpdatedEvent" do
      optional :data, :message, 1, "google.events.cloud.memcache.v1.InstanceEventData"
    end
    add_message "google.events.cloud.memcache.v1.InstanceDeletedEvent" do
      optional :data, :message, 1, "google.events.cloud.memcache.v1.InstanceEventData"
    end
  end
end

module Google
  module Events
    module Cloud
      module Memcache
        module V1
          InstanceCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.memcache.v1.InstanceCreatedEvent").msgclass
          InstanceUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.memcache.v1.InstanceUpdatedEvent").msgclass
          InstanceDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.memcache.v1.InstanceDeletedEvent").msgclass
        end
      end
    end
  end
end
