# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/auth/v2/events.proto

require 'google/protobuf'

require 'google/events/cloudevent_pb'
require 'google/events/firebase/auth/v2/data_pb'


descriptor_data = "\n+google/events/firebase/auth/v2/events.proto\x12\x1egoogle.events.firebase.auth.v2\x1a\x1egoogle/events/cloudevent.proto\x1a)google/events/firebase/auth/v2/data.proto\"\x87\x01\n\x10UserCreatedEvent\x12;\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32-.google.events.firebase.auth.v2.AuthEventData:6\xb2\xf8\xd8,$google.firebase.auth.user.v2.created\xca\xf8\xd8,\x08tenantid\"\x87\x01\n\x10UserUpdatedEvent\x12;\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32-.google.events.firebase.auth.v2.AuthEventData:6\xb2\xf8\xd8,$google.firebase.auth.user.v2.updated\xca\xf8\xd8,\x08tenantid\"\x87\x01\n\x10UserDeletedEvent\x12;\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32-.google.events.firebase.auth.v2.AuthEventData:6\xb2\xf8\xd8,$google.firebase.auth.user.v2.deleted\xca\xf8\xd8,\x08tenantidB\xf0\x01\n\"com.google.events.firebase.auth.v2\xaa\x02\'Google.Events.Protobuf.Firebase.Auth.V2\xca\x02\x1eGoogle\\Events\\Firebase\\Auth\\V2\xea\x02\"Google::Events::Firebase::Auth::V2\xba\xf8\xd8,\x17\x46irebase Authentication\xc2\xf8\xd8,;\n\x08tenantid\x12/The tenant ID associated with the user account.b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Google
  module Events
    module Firebase
      module Auth
        module V2
          UserCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.auth.v2.UserCreatedEvent").msgclass
          UserUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.auth.v2.UserUpdatedEvent").msgclass
          UserDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.auth.v2.UserDeletedEvent").msgclass
        end
      end
    end
  end
end
