# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/firebase/analytics/v1/events.proto

require 'google/protobuf'

require 'google/events/cloudevent_pb'
require 'google/events/firebase/analytics/v1/data_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/events/firebase/analytics/v1/events.proto", :syntax => :proto3) do
    add_message "google.events.firebase.analytics.v1.AnalyticsLogWrittenEvent" do
      optional :data, :message, 1, "google.events.firebase.analytics.v1.AnalyticsLogData"
    end
  end
end

module Google
  module Events
    module Firebase
      module Analytics
        module V1
          AnalyticsLogWrittenEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.firebase.analytics.v1.AnalyticsLogWrittenEvent").msgclass
        end
      end
    end
  end
end
