name: "Check Names"

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      head:
        description: "Commit reference at which to run tests"
        required: false
      base:
        description: "Commit reference from which to evaluate diffs"
        required: false
      flags:
        description: "Extra flags to pass to toys check-names"
        required: false

jobs:
  check-names:
    if: ${{ github.repository == 'googleapis/google-cloudevents-ruby' }}
    runs-on: ubuntu-latest
    steps:
      # 1. Setup Environment (Cross-Platform)
      # We force 'bash' so we can use standard linux syntax on Windows too.
      - name: Setup Gem Environment
        shell: bash
        run: |
          # Use the safe runner temp dir
          GEM_DIR="$RUNNER_TEMP/gem_home"

          # Export for future steps
          echo "GEM_HOME=$GEM_DIR" >> $GITHUB_ENV
          echo "GEM_PATH=$GEM_DIR" >> $GITHUB_ENV

          # Add bin to PATH so 'toys' would work
          echo "$GEM_DIR/bin" >> $GITHUB_PATH
      - name: Install Ruby 4.0
        uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b # v1.318.0
        with:
          ruby-version: "4.0"
          bundler-cache: false
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          gem install --no-document toys
      - name: Run CI
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_INPUTS_FLAGS: ${{ github.event.inputs.flags }}
        run: |
          toys check-names -v --github-event-name="$GITHUB_EVENT_NAME" --github-event-payload="${GITHUB_EVENT_PATH}" ${GITHUB_EVENT_INPUTS_FLAGS}
