name: "CI"

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI:
    if: ${{ github.repository == 'googleapis/google-cloudevents-ruby' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ruby: "3.2"
            tasks: "--test-unit"
          - os: ubuntu-latest
            ruby: "3.3"
            tasks: "--test-unit"
          - os: ubuntu-latest
            ruby: "3.4"
            tasks: "--test-unit"
          - os: ubuntu-latest
            ruby: "4.0"
            tasks: "--test-unit"
          - os: macos-latest
            ruby: "4.0"
            tasks: "--test-unit"
          - os: windows-latest
            ruby: "4.0"
            tasks: "--test-unit"
          - os: ubuntu-latest
            ruby: "4.0"
            tasks: "--test-rubocop --test-yardoc --test-build"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      # 1. Setup Environment (Cross-Platform)
      # We force 'bash' so we can use standard linux syntax on Windows too.
      - name: Setup Gem Environment
        shell: bash
        run: |
          # Use the safe runner temp dir
          GEM_DIR="$RUNNER_TEMP/gem_home"

          # Export for future steps
          echo "GEM_HOME=$GEM_DIR" >> $GITHUB_ENV
          echo "GEM_PATH=$GEM_DIR" >> $GITHUB_ENV

          # Add bin to PATH so 'toys' would work
          echo "$GEM_DIR/bin" >> $GITHUB_PATH
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b # v1.318.0
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: false
      - name: Install dependencies
        run: |
          gem install --no-document toys
      - name: Run CI
        run: |
          toys ci -v --only ${{ matrix.tasks }}
