name: Release-Please
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Gem version."
        required: false
      args:
        description: "Extra command line arguments."
        required: false

jobs:
  release-please:
    if: ${{ github.repository == 'googleapis/google-cloudevents-ruby' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Install NodeJS 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install tools
        run: |
          gem install --no-document toys
      - name: execute
        run: |
          toys release manifest -v \
            --fork --skip-labeling \
            --github-event-name=${{ github.event_name }} \
            ${{ github.event.inputs.args }} \
            -- .:${{ github.event.inputs.version }}
