# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/events/cloud/networkmanagement/v1/events.proto

require 'google/protobuf'

require 'google/events/cloud/networkmanagement/v1/data_pb'
require 'google/events/cloudevent_pb'


descriptor_data = "\n5google/events/cloud/networkmanagement/v1/events.proto\x12(google.events.cloud.networkmanagement.v1\x1a\x33google/events/cloud/networkmanagement/v1/data.proto\x1a\x1egoogle/events/cloudevent.proto\"\xbb\x01\n\x1c\x43onnectivityTestCreatedEvent\x12Q\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x43.google.events.cloud.networkmanagement.v1.ConnectivityTestEventData:H\xb2\xf8\xd8,:google.cloud.networkmanagement.connectivityTest.v1.created\xca\xf8\xd8,\x04test\"\xbb\x01\n\x1c\x43onnectivityTestUpdatedEvent\x12Q\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x43.google.events.cloud.networkmanagement.v1.ConnectivityTestEventData:H\xb2\xf8\xd8,:google.cloud.networkmanagement.connectivityTest.v1.updated\xca\xf8\xd8,\x04test\"\xbb\x01\n\x1c\x43onnectivityTestDeletedEvent\x12Q\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x43.google.events.cloud.networkmanagement.v1.ConnectivityTestEventData:H\xb2\xf8\xd8,:google.cloud.networkmanagement.connectivityTest.v1.deleted\xca\xf8\xd8,\x04testB\xe3\x01\xaa\x02\x31Google.Events.Protobuf.Cloud.NetworkManagement.V1\xca\x02(Google\\Events\\Cloud\\NetworkManagement\\V1\xea\x02,Google::Events::Cloud::NetworkManagement::V1\xba\xf8\xd8,\x12Network Management\xc2\xf8\xd8,9\n\x04test\x12\x31The resource ID of the Test triggering the event.b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
    ["google.events.cloud.networkmanagement.v1.ConnectivityTestEventData", "google/events/cloud/networkmanagement/v1/data.proto"],
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Google
  module Events
    module Cloud
      module NetworkManagement
        module V1
          ConnectivityTestCreatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.networkmanagement.v1.ConnectivityTestCreatedEvent").msgclass
          ConnectivityTestUpdatedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.networkmanagement.v1.ConnectivityTestUpdatedEvent").msgclass
          ConnectivityTestDeletedEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.events.cloud.networkmanagement.v1.ConnectivityTestDeletedEvent").msgclass
        end
      end
    end
  end
end
